image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/fabernovel/android:api-33-gcloud-ndk-v1.8.0

workflow:
  rules:
    - if: $CI_COMMIT_TAG

build-and-publish:
  stage: build
  variables:
    ORG_GRADLE_PROJECT_mavenCentralUsername: $MAVEN_CENTRAL_USERNAME
    ORG_GRADLE_PROJECT_mavenCentralPassword: $MAVEN_CENTRAL_PASSWORD
    ORG_GRADLE_PROJECT_signingInMemoryKey: $SONARTYPE_GPG_EXPORTED
    ORG_GRADLE_PROJECT_signingInMemoryKeyId: $SONATYPE_KEY_ID
    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: $SONATYPE_PASSWORD
  script:
    - mkdir ./.gradle/
    - echo nexusOptions.repositoryPassword=$NEXUS_PWD > ./.gradle/gradle.properties
    - echo nexusOptions.repositoryUsername=primerapi >> ./.gradle/gradle.properties
    - echo nexusOptions.stagingProfile=io.primer >> ./.gradle/gradle.properties
    - ./gradlew publish --stacktrace && ./gradlew closeAndReleaseRepository
  rules:
      - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - primer-ipay88-sdk-android/ipay88/build/outputs/aar/
  when: manual
