[versions]
kotlin = "1.8.20"
appcompat = "1.6.1"

ipay88 = "1.0.1"

# plugin versions
androidGradlePlugin = "8.1.3"
ktlint = "11.6.1"
artifactory = "4.24.15"

[libraries]
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
ipay = { group = "io.primer", name = "ipay88-my", version.ref = "ipay88" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jfrog-artifactory = {id = "com.jfrog.artifactory", version.ref = "artifactory"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
