name: Build SDK

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build release version of the SDK
        run: ./gradlew clean assembleRelease
