name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - default
          - alpha
          - beta
          - rc

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump release version and create changelog"
    steps:
      - name: Check out repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
      - name: Install cz
        run: pip install --user -U Commitizen
      - name: Record from version
        run: |
          echo "FROM_VERSION=$(cz version --project)" >> $GITHUB_ENV
      - name: Create release branch
        run: |
          git checkout -b release/next
          git push -u origin release/next
      # Bump version and create CHANGELOG - default release
      - name: Create bump and changelog
        if: ${{ inputs.releaseType == 'default' }}
        run: cz bump --files-only --yes --changelog
      # Bump version and create CHANGELOG - prereleasee
      - name: Create bump and changelog
        if: ${{ inputs.releaseType != 'default' }}
        run: cz bump --files-only --yes --changelog --prerelease ${{ inputs.releaseType }}
      - name: Record to version
        run: |
          echo "TO_VERSION=$(cz version --project)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83 # v6.0.4
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          base: main
          branch: release/next
          delete-branch: true
          title: Release ${{ env.TO_VERSION }}
          body: 'Bumped ${{ env.FROM_VERSION}} -> ${{ env.TO_VERSION }}'
