name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - release
          - release candidate
jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump release version and create changelog"
    steps:
      - name: Check out Release branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Create Release branch
        run: |
          git checkout -b release/next
          git push -u origin release/next
      - name: Create bump and changelog for release
        if: ${{ inputs.releaseType == 'release' }}
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: release/next
      - name: Create bump and changelog for release candidate
        if: ${{ inputs.releaseType == 'release candidate' }}
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: release/next
          prerelease: rc
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: master
          branch: release/next
          delete-branch: true
          title: Release ${{ steps.cz.outputs.version }}
          body: ''
